language: java

script: make

sudo: false

jdk:
  - oraclejdk8
#  - oraclejdk7
  - openjdk7

notifications:
  email:
    - mernst@cs.washington.edu

after_success:
  # The vertical bar (pipe) means multi-line command in YAML.
  - |
       if [[ ($TRAVIS_PULL_REQUEST == false) &&
             ( (! $TRAVIS_JOB_NUMBER == *.*) || ($TRAVIS_JOB_NUMBER == *.1) ) ]] ; then
        curl -LO https://raw.github.com/mernst/plume-lib/master/bin/trigger-travis.sh
        sh trigger-travis.sh codespecs daikon $TRAVISTOKEN
        sh trigger-travis.sh typetools plume-lib-typecheck $TRAVISTOKEN
      fi
